'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("127.0.0.1")>  _
        Public Property OBSHost() As String
            Get
                Return CType(Me("OBSHost"),String)
            End Get
            Set
                Me("OBSHost") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("4444")>  _
        Public Property OBSPort() As String
            Get
                Return CType(Me("OBSPort"),String)
            End Get
            Set
                Me("OBSPort") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("password")>  _
        Public Property OBSPass() As String
            Get
                Return CType(Me("OBSPass"),String)
            End Get
            Set
                Me("OBSPass") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property TwitchUsername() As String
            Get
                Return CType(Me("TwitchUsername"),String)
            End Get
            Set
                Me("TwitchUsername") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property TwitchOAuth() As String
            Get
                Return CType(Me("TwitchOAuth"),String)
            End Get
            Set
                Me("TwitchOAuth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property TwitchChannel() As String
            Get
                Return CType(Me("TwitchChannel"),String)
            End Get
            Set
                Me("TwitchChannel") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("[OW] Vote1")>  _
        Public Property OBSSceneVote1() As String
            Get
                Return CType(Me("OBSSceneVote1"),String)
            End Get
            Set
                Me("OBSSceneVote1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("[OW] Vote2")>  _
        Public Property OBSSceneVote2() As String
            Get
                Return CType(Me("OBSSceneVote2"),String)
            End Get
            Set
                Me("OBSSceneVote2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("[OW] Vote3")>  _
        Public Property OBSSceneVote3() As String
            Get
                Return CType(Me("OBSSceneVote3"),String)
            End Get
            Set
                Me("OBSSceneVote3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Vote Bar1")>  _
        Public Property OBSSourceBar1() As String
            Get
                Return CType(Me("OBSSourceBar1"),String)
            End Get
            Set
                Me("OBSSourceBar1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Vote Bar2")>  _
        Public Property OBSSourceBar2() As String
            Get
                Return CType(Me("OBSSourceBar2"),String)
            End Get
            Set
                Me("OBSSourceBar2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Vote Bar3")>  _
        Public Property OBSSourceBar3() As String
            Get
                Return CType(Me("OBSSourceBar3"),String)
            End Get
            Set
                Me("OBSSourceBar3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("[Nest] Overwatch Vote")>  _
        Public Property OBSSceneOverwatch() As String
            Get
                Return CType(Me("OBSSceneOverwatch"),String)
            End Get
            Set
                Me("OBSSceneOverwatch") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LookFor() As String
            Get
                Return CType(Me("LookFor"),String)
            End Get
            Set
                Me("LookFor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property chkHero01() As Boolean
            Get
                Return CType(Me("chkHero01"),Boolean)
            End Get
            Set
                Me("chkHero01") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property chkHero02() As Boolean
            Get
                Return CType(Me("chkHero02"),Boolean)
            End Get
            Set
                Me("chkHero02") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property chkHero03() As Boolean
            Get
                Return CType(Me("chkHero03"),Boolean)
            End Get
            Set
                Me("chkHero03") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property chkHero04() As Boolean
            Get
                Return CType(Me("chkHero04"),Boolean)
            End Get
            Set
                Me("chkHero04") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property chkHero05() As Boolean
            Get
                Return CType(Me("chkHero05"),Boolean)
            End Get
            Set
                Me("chkHero05") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property chkHero06() As Boolean
            Get
                Return CType(Me("chkHero06"),Boolean)
            End Get
            Set
                Me("chkHero06") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property chkHero07() As Boolean
            Get
                Return CType(Me("chkHero07"),Boolean)
            End Get
            Set
                Me("chkHero07") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property chkHero08() As Boolean
            Get
                Return CType(Me("chkHero08"),Boolean)
            End Get
            Set
                Me("chkHero08") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property chkHero09() As Boolean
            Get
                Return CType(Me("chkHero09"),Boolean)
            End Get
            Set
                Me("chkHero09") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property chkHero10() As Boolean
            Get
                Return CType(Me("chkHero10"),Boolean)
            End Get
            Set
                Me("chkHero10") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property chkHero11() As Boolean
            Get
                Return CType(Me("chkHero11"),Boolean)
            End Get
            Set
                Me("chkHero11") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property chkHero12() As Boolean
            Get
                Return CType(Me("chkHero12"),Boolean)
            End Get
            Set
                Me("chkHero12") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property chkHero13() As Boolean
            Get
                Return CType(Me("chkHero13"),Boolean)
            End Get
            Set
                Me("chkHero13") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property chkHero14() As Boolean
            Get
                Return CType(Me("chkHero14"),Boolean)
            End Get
            Set
                Me("chkHero14") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property chkHero15() As Boolean
            Get
                Return CType(Me("chkHero15"),Boolean)
            End Get
            Set
                Me("chkHero15") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property chkHero16() As Boolean
            Get
                Return CType(Me("chkHero16"),Boolean)
            End Get
            Set
                Me("chkHero16") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property chkHero17() As Boolean
            Get
                Return CType(Me("chkHero17"),Boolean)
            End Get
            Set
                Me("chkHero17") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property chkHero18() As Boolean
            Get
                Return CType(Me("chkHero18"),Boolean)
            End Get
            Set
                Me("chkHero18") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property chkHero19() As Boolean
            Get
                Return CType(Me("chkHero19"),Boolean)
            End Get
            Set
                Me("chkHero19") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property chkHero20() As Boolean
            Get
                Return CType(Me("chkHero20"),Boolean)
            End Get
            Set
                Me("chkHero20") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property chkHero21() As Boolean
            Get
                Return CType(Me("chkHero21"),Boolean)
            End Get
            Set
                Me("chkHero21") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property chkHero22() As Boolean
            Get
                Return CType(Me("chkHero22"),Boolean)
            End Get
            Set
                Me("chkHero22") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property chkHero23() As Boolean
            Get
                Return CType(Me("chkHero23"),Boolean)
            End Get
            Set
                Me("chkHero23") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property chkHero24() As Boolean
            Get
                Return CType(Me("chkHero24"),Boolean)
            End Get
            Set
                Me("chkHero24") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property chkHero25() As Boolean
            Get
                Return CType(Me("chkHero25"),Boolean)
            End Get
            Set
                Me("chkHero25") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property chkHero26() As Boolean
            Get
                Return CType(Me("chkHero26"),Boolean)
            End Get
            Set
                Me("chkHero26") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property chkHero27() As Boolean
            Get
                Return CType(Me("chkHero27"),Boolean)
            End Get
            Set
                Me("chkHero27") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("251")>  _
        Public Property Bar1Y() As Integer
            Get
                Return CType(Me("Bar1Y"),Integer)
            End Get
            Set
                Me("Bar1Y") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("385")>  _
        Public Property Bar2Y() As Integer
            Get
                Return CType(Me("Bar2Y"),Integer)
            End Get
            Set
                Me("Bar2Y") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("518")>  _
        Public Property Bar3Y() As Integer
            Get
                Return CType(Me("Bar3Y"),Integer)
            End Get
            Set
                Me("Bar3Y") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("960")>  _
        Public Property ReticleX() As Integer
            Get
                Return CType(Me("ReticleX"),Integer)
            End Get
            Set
                Me("ReticleX") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("540")>  _
        Public Property ReticleY() As Integer
            Get
                Return CType(Me("ReticleY"),Integer)
            End Get
            Set
                Me("ReticleY") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.Overwatch_Hero_2._0.My.MySettings
            Get
                Return Global.Overwatch_Hero_2._0.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
